import type { ScheduleMode } from "@/lib/codex-automation-form";

export type AutomationTemplate = {
  id: string;
  emoji: string;
  /** Short automation name pre-filled in the "Name" field. */
  name: string;
  /** Task description shown on the card and used as the goals pre-fill. */
  title: string;
  /** Human-readable schedule shown on the card. */
  scheduleLabel: string;
  scheduleMode: ScheduleMode;
  /** "HH:MM" — used when scheduleMode is "daily" or "weekly". */
  time: string;
  /** RRULE weekday codes — used when scheduleMode is "weekly". */
  days: string[];
  /** Full RRULE string — used when scheduleMode is "raw". */
  rawRrule: string;
  goals: string;
  category: string;
};

export const AUTOMATION_TEMPLATES: AutomationTemplate[] = [
  // ── System ────────────────────────────────────────────────────────────────
  {
    id: "bug-scan",
    emoji: "🔴",
    name: "Daily bug scan",
    title: "Scan recent commits (since the last run, or last 24h) for likely bugs and propose minimal fixes.",
    scheduleLabel: "Daily at 9:00 AM",
    scheduleMode: "daily",
    time: "09:00",
    days: [],
    rawRrule: "",
    goals: "Scan recent git commits since the last run (or the past 24 hours, whichever is shorter) for likely bugs. For each issue found, propose a minimal fix with a clear explanation of the root cause.",
    category: "System",
  },
  {
    id: "release-notes",
    emoji: "📋",
    name: "Weekly release notes",
    title: "Draft weekly release notes from merged PRs (include links when available).",
    scheduleLabel: "Fridays at 8:00 AM",
    scheduleMode: "weekly",
    time: "08:00",
    days: ["FR"],
    rawRrule: "",
    goals: "Draft this week's release notes from merged pull requests. Include PR titles, authors, and links where available. Group by feature, fix, and chore. Keep the tone concise and user-facing.",
    category: "System",
  },
  {
    id: "standup-summary",
    emoji: "💬",
    name: "Git standup summary",
    title: "Summarize yesterday's git activity for standup.",
    scheduleLabel: "Weekdays at 9:00 AM",
    scheduleMode: "weekly",
    time: "09:00",
    days: ["MO", "TU", "WE", "TH", "FR"],
    rawRrule: "",
    goals: "Summarize yesterday's git activity — commits, PRs opened/merged, and review comments — into a concise standup update. Highlight anything blocked or needing attention.",
    category: "System",
  },
  {
    id: "ci-failures",
    emoji: "🟡",
    name: "CI failure digest",
    title: "Summarize CI failures and flaky tests from the last CI window; suggest top fixes.",
    scheduleLabel: "Daily at 9:00 PM",
    scheduleMode: "daily",
    time: "21:00",
    days: [],
    rawRrule: "",
    goals: "Summarize today's CI failures and flaky test runs. Group by root cause where possible and suggest the highest-leverage fixes. Flag any tests that have been consistently failing.",
    category: "System",
  },
  {
    id: "game-prototype",
    emoji: "🎮",
    name: "Daily game prototype",
    title: "Create a small classic game with minimal scope.",
    scheduleLabel: "Daily at 2:00 PM",
    scheduleMode: "daily",
    time: "14:00",
    days: [],
    rawRrule: "",
    goals: "Prototype one small, playable classic game (e.g. snake, breakout, pong, minesweeper). Keep scope minimal — a single file or a handful of files. Focus on a working game loop, not polish.",
    category: "System",
  },
  {
    id: "skill-suggestions",
    emoji: "👤",
    name: "Skill growth suggestions",
    title: "From recent PRs and reviews, suggest next skills to deepen.",
    scheduleLabel: "Fridays at 10:00 AM",
    scheduleMode: "weekly",
    time: "10:00",
    days: ["FR"],
    rawRrule: "",
    goals: "Review this week's pull requests and code reviews to identify patterns in the codebase. Suggest 2–3 specific technical skills or concepts worth deepening based on what came up most frequently.",
    category: "System",
  },
  {
    id: "weekly-update",
    emoji: "📊",
    name: "Weekly engineering update",
    title: "Synthesize this week's PRs, rollouts, incidents, and reviews into a weekly update.",
    scheduleLabel: "Fridays at 4:00 PM",
    scheduleMode: "weekly",
    time: "16:00",
    days: ["FR"],
    rawRrule: "",
    goals: "Synthesize this week's pull requests, production rollouts, incidents, and peer reviews into a concise weekly engineering update. Highlight wins, blockers, and key decisions. Keep it under one page.",
    category: "System",
  },
  {
    id: "perf-regressions",
    emoji: "📈",
    name: "Performance regression check",
    title: "Compare recent changes to benchmarks or traces and flag regressions early.",
    scheduleLabel: "Daily at 9:00 AM",
    scheduleMode: "daily",
    time: "09:00",
    days: [],
    rawRrule: "",
    goals: "Compare recent code changes against available benchmarks, profiling traces, or performance metrics. Flag any regressions early with details on which change likely caused them and a suggested investigation path.",
    category: "System",
  },
  {
    id: "dependency-drift",
    emoji: "🔍",
    name: "Dependency drift audit",
    title: "Detect dependency and SDK drift and propose a minimal alignment plan.",
    scheduleLabel: "Daily at 11:00 AM",
    scheduleMode: "daily",
    time: "11:00",
    days: [],
    rawRrule: "",
    goals: "Detect dependencies and SDKs that have drifted from their pinned or expected versions. Propose a minimal, low-risk alignment plan — flag breaking changes and defer non-critical upgrades.",
    category: "System",
  },
  {
    id: "untested-paths",
    emoji: "✅",
    name: "Untested path finder",
    title: "Identify untested paths from recent changes; add focused tests and use $yeet for draft PRs.",
    scheduleLabel: "Daily at 3:00 PM",
    scheduleMode: "daily",
    time: "15:00",
    days: [],
    rawRrule: "",
    goals: "Identify code paths introduced or modified by recent commits that lack test coverage. Write focused unit or integration tests for the highest-risk paths. Use $yeet to open a draft PR with the new tests.",
    category: "System",
  },
  {
    id: "pre-tag-checklist",
    emoji: "🏷️",
    name: "Pre-release checklist",
    title: "Before tagging, verify changelog, migrations, feature flags, and tests.",
    scheduleLabel: "Thursdays at 1:00 PM",
    scheduleMode: "weekly",
    time: "13:00",
    days: ["TH"],
    rawRrule: "",
    goals: "Run through the pre-release checklist: verify the CHANGELOG is up to date, check for pending database migrations, confirm feature flags are in the expected state, and ensure all tests are green. Surface any blockers.",
    category: "System",
  },
  {
    id: "agents-md-update",
    emoji: "📝",
    name: "AGENTS.md updater",
    title: "Update AGENTS.md with newly discovered workflows and commands.",
    scheduleLabel: "Fridays at 11:00 AM",
    scheduleMode: "weekly",
    time: "11:00",
    days: ["FR"],
    rawRrule: "",
    goals: "Review this week's work for newly discovered commands, workflows, shortcuts, or conventions that should be documented. Update AGENTS.md with concise entries for each. Keep entries terse and action-oriented.",
    category: "System",
  },
  {
    id: "pr-teammate-summary",
    emoji: "👥",
    name: "Team PR summary",
    title: "Summarize last week's PRs by teammate and theme; highlight risks.",
    scheduleLabel: "Mondays at 9:00 AM",
    scheduleMode: "weekly",
    time: "09:00",
    days: ["MO"],
    rawRrule: "",
    goals: "Summarize last week's merged and open pull requests grouped by teammate and theme. Highlight any PRs that look risky (large diffs, missing tests, touching critical paths) and flag them for follow-up.",
    category: "System",
  },
  {
    id: "issue-triage",
    emoji: "🔖",
    name: "Issue triage",
    title: "Triage new issues; suggest owner, priority, and labels.",
    scheduleLabel: "Weekdays at 9:30 AM",
    scheduleMode: "weekly",
    time: "09:30",
    days: ["MO", "TU", "WE", "TH", "FR"],
    rawRrule: "",
    goals: "Triage newly opened issues. For each issue suggest an appropriate owner, a priority (P0–P3), and one or more labels based on the content and affected area. Flag any that look like duplicates or need more information.",
    category: "System",
  },
  {
    id: "ci-failure-grouping",
    emoji: "🔴",
    name: "CI failure grouper",
    title: "Check CI failures; group by likely root cause and suggest minimal fixes.",
    scheduleLabel: "Every 2 hours on weekdays",
    scheduleMode: "raw",
    time: "09:00",
    days: [],
    rawRrule: "RRULE:FREQ=HOURLY;INTERVAL=2;BYDAY=MO,TU,WE,TH,FR",
    goals: "Check the most recent CI failures across all branches. Group them by likely root cause (e.g. flaky test, environment issue, real regression). For each group propose the minimal fix needed to unblock builds.",
    category: "System",
  },
  {
    id: "dep-upgrades",
    emoji: "🔬",
    name: "Dependency upgrade scan",
    title: "Scan outdated dependencies; propose safe upgrades with minimal changes.",
    scheduleLabel: "Every 30 days",
    scheduleMode: "raw",
    time: "11:00",
    days: [],
    rawRrule: "RRULE:FREQ=DAILY;INTERVAL=30",
    goals: "Scan all dependencies for available upgrades. Separate safe patch/minor upgrades from potentially breaking major upgrades. Propose a minimal, reviewable upgrade plan with changelog highlights for major bumps.",
    category: "System",
  },
  {
    id: "perf-audit",
    emoji: "📈",
    name: "Performance audit",
    title: "Audit performance regressions and propose highest-leverage fixes.",
    scheduleLabel: "Mondays at 2:00 PM",
    scheduleMode: "weekly",
    time: "14:00",
    days: ["MO"],
    rawRrule: "",
    goals: "Audit recent performance data — build times, bundle sizes, API latencies, or runtime benchmarks — and identify the highest-leverage regressions. Propose targeted fixes ordered by impact-to-effort ratio.",
    category: "System",
  },
  {
    id: "changelog-update",
    emoji: "✏️",
    name: "Changelog update",
    title: "Update the changelog with this week's highlights and key PR links.",
    scheduleLabel: "Fridays at 4:00 PM",
    scheduleMode: "weekly",
    time: "16:00",
    days: ["FR"],
    rawRrule: "",
    goals: "Update the CHANGELOG with this week's most significant merged PRs. Group by feature, fix, and internal. Include PR links. Write in user-facing language — no internal jargon or ticket IDs.",
    category: "System",
  },
];

export const TEMPLATE_CATEGORIES = [...new Set(AUTOMATION_TEMPLATES.map((t) => t.category))];
