// GENERATED by scripts/sync-runtimes.mjs — do not edit by hand.
// Re-generate with: pnpm sync:runtimes
//
// Source: OpenCoven/coven-runtimes canonical registry index
//   ref:      main
//   blob sha: b1c23ce0d8577f2e808472c39795c6a726b75a7b
//
// Every entry passed coven-runtimes acceptance (conformance + review), so
// Cave treats these as trusted runtimes (see harness-adapters.ts). New
// runtimes get a generic glyph until someone adds a brand mark in
// runtime-logo.tsx — that polish stays a deliberate manual step.

export type RegistryRuntimeCapabilities = {
  stream: boolean;
  preassignedSessionId: boolean;
  think: boolean;
  speed: boolean;
};

export type RegistryRuntime = {
  id: string;
  label: string;
  binary: string;
  installHint: string;
  version: string;
  homepage?: string;
  description?: string;
  /** CLI flag that forwards a model id, when the runtime supports one. */
  modelFlag: string | null;
  capabilities: RegistryRuntimeCapabilities;
  /** The full `$COVEN_HOME/adapters/<id>.json` document for this runtime. */
  adapterManifest: unknown;
};

export const REGISTRY_SOURCE = {
  repo: "OpenCoven/coven-runtimes",
  ref: "main",
  blobSha: "b1c23ce0d8577f2e808472c39795c6a726b75a7b",
} as const;

export const REGISTRY_RUNTIMES: RegistryRuntime[] = [
  {
    "id": "copilot",
    "label": "GitHub Copilot CLI",
    "binary": "copilot",
    "installHint": "npm install -g @github/copilot (or `brew install copilot-cli`), then run `copilot login` and ensure `copilot` is on PATH.",
    "version": "1.0.0",
    "homepage": "https://docs.github.com/en/copilot/concepts/agents/about-copilot-cli",
    "description": "GitHub Copilot CLI adapter. One-shot via `-s -p`, interactive via `-i`, JSONL streaming via `--output-format json --stream on`, session pre-assignment/resume via `--session-id`/`--resume`. Permission mapping uses the argv-list sandbox form because Copilot's flags are boolean/repeatable (`--allow-all`; `--deny-tool write --deny-tool shell`) rather than a single `--flag value` pair.",
    "modelFlag": "--model",
    "capabilities": {
      "stream": true,
      "preassignedSessionId": true,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "copilot",
          "label": "GitHub Copilot CLI",
          "executable": "copilot",
          "interactive_prompt_prefix_args": [
            "-i"
          ],
          "non_interactive_prompt_prefix_args": [
            "-s",
            "-p"
          ],
          "install_hint": "npm install -g @github/copilot (or `brew install copilot-cli`), then run `copilot login` and ensure `copilot` is on PATH.",
          "model_flag": "--model",
          "capabilities": {
            "stream": true,
            "preassigned_session_id": true,
            "think": false,
            "speed": false
          },
          "sandbox": {
            "full_args": [
              "--allow-all"
            ],
            "read_only_args": [
              "--deny-tool",
              "write",
              "--deny-tool",
              "shell"
            ]
          },
          "stream_args": {
            "prefix_args": [
              "--output-format",
              "json",
              "--stream",
              "on",
              "-p"
            ],
            "session_id_flag": "--session-id",
            "resume_flag": "--resume"
          },
          "version": "1.0.0",
          "homepage": "https://docs.github.com/en/copilot/concepts/agents/about-copilot-cli",
          "description": "GitHub Copilot CLI adapter. One-shot via `-s -p`, interactive via `-i`, JSONL streaming via `--output-format json --stream on`, session pre-assignment/resume via `--session-id`/`--resume`. Permission mapping uses the argv-list sandbox form because Copilot's flags are boolean/repeatable (`--allow-all`; `--deny-tool write --deny-tool shell`) rather than a single `--flag value` pair."
        }
      ]
    }
  },
  {
    "id": "grok",
    "label": "Grok Build",
    "binary": "grok",
    "installHint": "Install Grok Build by following xAI's official instructions at https://docs.x.ai/build/overview. Make sure `grok` is on PATH and run `grok login` (or set XAI_API_KEY for headless auth), then retry `coven adapter doctor grok`.",
    "version": "1.0.0",
    "homepage": "https://docs.x.ai/build/cli/headless-scripting",
    "description": "xAI Grok Build adapter. Finite one-shot headless runs via `--single=<prompt>` in Grok's plain output mode (`--output-format plain`, its own default): stdout carries only the final response text, reasoning is dropped at the source, and errors go to stderr — no event protocol or translation layer. Session pre-assignment via `--session-id`, cold-start resume via `--resume`. Permission mapping uses the argv-list sandbox form to drive both `--permission-mode` and `--sandbox`. No stream mode: every turn is a fresh process.",
    "modelFlag": "--model",
    "capabilities": {
      "stream": false,
      "preassignedSessionId": true,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "grok",
          "label": "Grok Build",
          "executable": "grok",
          "interactive_prompt_prefix_args": [
            "--no-auto-update",
            "--no-alt-screen",
            "--output-format",
            "plain"
          ],
          "non_interactive_prompt_prefix_args": [
            "--no-auto-update",
            "--no-alt-screen",
            "--output-format",
            "plain"
          ],
          "prompt_flag": "--single",
          "interactive_prompt_flag": "--single",
          "install_hint": "Install Grok Build by following xAI's official instructions at https://docs.x.ai/build/overview. Make sure `grok` is on PATH and run `grok login` (or set XAI_API_KEY for headless auth), then retry `coven adapter doctor grok`.",
          "system_prompt_flag": "--rules",
          "model_flag": "--model",
          "capabilities": {
            "stream": false,
            "preassigned_session_id": true,
            "think": false,
            "speed": false
          },
          "sandbox": {
            "full_args": [
              "--permission-mode",
              "bypassPermissions",
              "--sandbox",
              "off"
            ],
            "read_only_args": [
              "--permission-mode",
              "default",
              "--sandbox",
              "read-only"
            ]
          },
          "continuity_args": {
            "init_prefix_args": [
              "--no-auto-update",
              "--no-alt-screen",
              "--output-format",
              "plain"
            ],
            "resume_prefix_args": [
              "--no-auto-update",
              "--no-alt-screen",
              "--output-format",
              "plain"
            ],
            "session_id_flag": "--session-id",
            "resume_flag": "--resume"
          },
          "version": "1.0.0",
          "homepage": "https://docs.x.ai/build/cli/headless-scripting",
          "description": "xAI Grok Build adapter. Finite one-shot headless runs via `--single=<prompt>` in Grok's plain output mode (`--output-format plain`, its own default): stdout carries only the final response text, reasoning is dropped at the source, and errors go to stderr — no event protocol or translation layer. Session pre-assignment via `--session-id`, cold-start resume via `--resume`. Permission mapping uses the argv-list sandbox form to drive both `--permission-mode` and `--sandbox`. No stream mode: every turn is a fresh process."
        }
      ]
    }
  },
  {
    "id": "hermes",
    "label": "Hermes Agent",
    "binary": "hermes-coven",
    "installHint": "Install Hermes Agent, add it to PATH, install the hermes-coven shim, and complete Hermes setup before using this adapter.",
    "version": "1.0.2",
    "description": "Hermes adapter with native model forwarding. Uses the hermes-coven shim so the harness trailing positional prompt is remapped to hermes chat -q/--query without changing model arguments.",
    "modelFlag": "--model",
    "capabilities": {
      "stream": false,
      "preassignedSessionId": false,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "hermes",
          "label": "Hermes Agent",
          "executable": "hermes-coven",
          "interactive_prompt_prefix_args": [
            "chat",
            "--source",
            "coven"
          ],
          "non_interactive_prompt_prefix_args": [
            "chat",
            "--source",
            "coven",
            "-Q"
          ],
          "install_hint": "Install Hermes Agent, add it to PATH, install the hermes-coven shim, and complete Hermes setup before using this adapter.",
          "model_flag": "--model",
          "capabilities": {
            "stream": false,
            "preassigned_session_id": false,
            "think": false,
            "speed": false
          },
          "version": "1.0.2",
          "description": "Hermes adapter with native model forwarding. Uses the hermes-coven shim so the harness trailing positional prompt is remapped to hermes chat -q/--query without changing model arguments."
        }
      ]
    }
  },
  {
    "id": "opencode",
    "label": "OpenCode",
    "binary": "opencode",
    "installHint": "Install OpenCode from https://opencode.ai/docs/cli (e.g. `npm i -g opencode-ai`) and ensure `opencode` resolves on PATH. Verify with `opencode run --help` — the similarly-named Go app some package managers ship has no `run` subcommand and will not work.",
    "version": "0.1.0",
    "homepage": "https://opencode.ai",
    "description": "OpenCode runtime adapter for Coven. Drives `opencode run` in non-interactive mode; system prompts and tools are configured via the OpenCode project config (AGENTS.md / opencode.json), not via CLI flags.",
    "modelFlag": "--model",
    "capabilities": {
      "stream": false,
      "preassignedSessionId": false,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "opencode",
          "label": "OpenCode",
          "executable": "opencode",
          "interactive_prompt_prefix_args": [],
          "non_interactive_prompt_prefix_args": [
            "run"
          ],
          "install_hint": "Install OpenCode from https://opencode.ai/docs/cli (e.g. `npm i -g opencode-ai`) and ensure `opencode` resolves on PATH. Verify with `opencode run --help` — the similarly-named Go app some package managers ship has no `run` subcommand and will not work.",
          "model_flag": "--model",
          "capabilities": {
            "stream": false,
            "preassigned_session_id": false,
            "think": false,
            "speed": false
          },
          "version": "0.1.0",
          "homepage": "https://opencode.ai",
          "description": "OpenCode runtime adapter for Coven. Drives `opencode run` in non-interactive mode; system prompts and tools are configured via the OpenCode project config (AGENTS.md / opencode.json), not via CLI flags."
        }
      ]
    }
  }
];
