// GENERATED by scripts/sync-runtimes.mjs — do not edit by hand.
// Re-generate with: pnpm sync:runtimes
//
// Source: OpenCoven/coven-runtimes canonical registry index
//   ref:      v0.2.0
//   blob sha: ced69d5b532f7c1478a1f45d00c0701ab948e221
//
// Every entry passed coven-runtimes acceptance (conformance + review), so
// Cave treats these as trusted runtimes (see harness-adapters.ts). New
// runtimes get a generic glyph until someone adds a brand mark in
// runtime-logo.tsx — that polish stays a deliberate manual step.

export type RegistryRuntimeCapabilities = {
  stream: boolean;
  preassignedSessionId: boolean;
  think: boolean;
  speed: boolean;
};

export type RegistryModelIdTransform = "strip_provider" | "preserve";

export type RegistryRuntime = {
  id: string;
  label: string;
  binary: string;
  installHint: string;
  version: string;
  homepage?: string;
  description?: string;
  /** CLI flag that forwards a model id, when the runtime supports one. */
  modelFlag: string | null;
  /** How provider-qualified model ids are forwarded to this runtime. */
  modelIdTransform: RegistryModelIdTransform;
  capabilities: RegistryRuntimeCapabilities;
  /** The full `$COVEN_HOME/adapters/<id>.json` document for this runtime. */
  adapterManifest: unknown;
};

export const REGISTRY_SOURCE = {
  repo: "OpenCoven/coven-runtimes",
  ref: "v0.2.0",
  blobSha: "ced69d5b532f7c1478a1f45d00c0701ab948e221",
} as const;

export const REGISTRY_RUNTIMES: RegistryRuntime[] = [
  {
    "id": "copilot",
    "label": "GitHub Copilot CLI",
    "binary": "copilot",
    "installHint": "npm install -g @github/copilot (or `brew install copilot-cli`), then run `copilot login` and ensure `copilot` is on PATH.",
    "version": "1.0.0",
    "homepage": "https://docs.github.com/en/copilot/concepts/agents/about-copilot-cli",
    "description": "GitHub Copilot CLI adapter. One-shot via `-s -p`, interactive via `-i`, JSONL streaming via `--output-format json --stream on`, session pre-assignment/resume via `--session-id`/`--resume`. Permission mapping uses the argv-list sandbox form because Copilot's flags are boolean/repeatable (`--allow-all`; `--deny-tool write --deny-tool shell`) rather than a single `--flag value` pair.",
    "modelFlag": "--model",
    "modelIdTransform": "strip_provider",
    "capabilities": {
      "stream": true,
      "preassignedSessionId": true,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "copilot",
          "label": "GitHub Copilot CLI",
          "executable": "copilot",
          "interactive_prompt_prefix_args": [
            "-i"
          ],
          "non_interactive_prompt_prefix_args": [
            "-s",
            "-p"
          ],
          "install_hint": "npm install -g @github/copilot (or `brew install copilot-cli`), then run `copilot login` and ensure `copilot` is on PATH.",
          "model_flag": "--model",
          "capabilities": {
            "stream": true,
            "preassigned_session_id": true,
            "think": false,
            "speed": false
          },
          "sandbox": {
            "full_args": [
              "--allow-all"
            ],
            "read_only_args": [
              "--deny-tool",
              "write",
              "--deny-tool",
              "shell"
            ]
          },
          "stream_args": {
            "prefix_args": [
              "--output-format",
              "json",
              "--stream",
              "on",
              "-p"
            ],
            "session_id_flag": "--session-id",
            "resume_flag": "--resume"
          },
          "version": "1.0.0",
          "homepage": "https://docs.github.com/en/copilot/concepts/agents/about-copilot-cli",
          "description": "GitHub Copilot CLI adapter. One-shot via `-s -p`, interactive via `-i`, JSONL streaming via `--output-format json --stream on`, session pre-assignment/resume via `--session-id`/`--resume`. Permission mapping uses the argv-list sandbox form because Copilot's flags are boolean/repeatable (`--allow-all`; `--deny-tool write --deny-tool shell`) rather than a single `--flag value` pair."
        }
      ]
    }
  },
  {
    "id": "grok",
    "label": "Grok Build",
    "binary": "grok",
    "installHint": "Install Grok Build by following xAI's official instructions at https://docs.x.ai/build/overview. Make sure `grok` is on PATH and run `grok login` (or set XAI_API_KEY for headless auth), then retry `coven adapter doctor grok`.",
    "version": "1.0.0",
    "homepage": "https://docs.x.ai/build/cli/headless-scripting",
    "description": "xAI Grok Build adapter. Finite one-shot headless runs via `--single=<prompt>` in Grok's plain output mode (`--output-format plain`, its own default): stdout carries only the final response text, reasoning is dropped at the source, and errors go to stderr — no event protocol or translation layer. Session pre-assignment via `--session-id`, cold-start resume via `--resume`. Permission mapping uses the argv-list sandbox form to drive both `--permission-mode` and `--sandbox`. No stream mode: every turn is a fresh process.",
    "modelFlag": "--model",
    "modelIdTransform": "strip_provider",
    "capabilities": {
      "stream": false,
      "preassignedSessionId": true,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "grok",
          "label": "Grok Build",
          "executable": "grok",
          "interactive_prompt_prefix_args": [
            "--no-auto-update",
            "--no-alt-screen",
            "--output-format",
            "plain"
          ],
          "non_interactive_prompt_prefix_args": [
            "--no-auto-update",
            "--no-alt-screen",
            "--output-format",
            "plain"
          ],
          "prompt_flag": "--single",
          "interactive_prompt_flag": "--single",
          "install_hint": "Install Grok Build by following xAI's official instructions at https://docs.x.ai/build/overview. Make sure `grok` is on PATH and run `grok login` (or set XAI_API_KEY for headless auth), then retry `coven adapter doctor grok`.",
          "system_prompt_flag": "--rules",
          "model_flag": "--model",
          "capabilities": {
            "stream": false,
            "preassigned_session_id": true,
            "think": false,
            "speed": false
          },
          "sandbox": {
            "full_args": [
              "--permission-mode",
              "bypassPermissions",
              "--sandbox",
              "off"
            ],
            "read_only_args": [
              "--permission-mode",
              "default",
              "--sandbox",
              "read-only"
            ]
          },
          "continuity_args": {
            "init_prefix_args": [
              "--no-auto-update",
              "--no-alt-screen",
              "--output-format",
              "plain"
            ],
            "resume_prefix_args": [
              "--no-auto-update",
              "--no-alt-screen",
              "--output-format",
              "plain"
            ],
            "session_id_flag": "--session-id",
            "resume_flag": "--resume"
          },
          "version": "1.0.0",
          "homepage": "https://docs.x.ai/build/cli/headless-scripting",
          "description": "xAI Grok Build adapter. Finite one-shot headless runs via `--single=<prompt>` in Grok's plain output mode (`--output-format plain`, its own default): stdout carries only the final response text, reasoning is dropped at the source, and errors go to stderr — no event protocol or translation layer. Session pre-assignment via `--session-id`, cold-start resume via `--resume`. Permission mapping uses the argv-list sandbox form to drive both `--permission-mode` and `--sandbox`. No stream mode: every turn is a fresh process."
        }
      ]
    }
  },
  {
    "id": "hermes",
    "label": "Hermes Agent",
    "binary": "hermes",
    "installHint": "Install and complete setup for Hermes Agent from https://github.com/NousResearch/hermes-agent, then ensure the native `hermes` executable resolves on PATH.",
    "version": "1.0.3",
    "description": "Hermes adapter using the native `hermes chat` executable and `--query` prompt binding while preserving provider-qualified model IDs.",
    "modelFlag": "--model",
    "modelIdTransform": "preserve",
    "capabilities": {
      "stream": false,
      "preassignedSessionId": false,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "hermes",
          "label": "Hermes Agent",
          "executable": "hermes",
          "interactive_prompt_prefix_args": [
            "chat",
            "--source",
            "coven"
          ],
          "non_interactive_prompt_prefix_args": [
            "chat",
            "--source",
            "coven",
            "-Q"
          ],
          "prompt_flag": "--query",
          "interactive_prompt_flag": "--query",
          "install_hint": "Install and complete setup for Hermes Agent from https://github.com/NousResearch/hermes-agent, then ensure the native `hermes` executable resolves on PATH.",
          "model_flag": "--model",
          "model_id_transform": "preserve",
          "capabilities": {
            "stream": false,
            "preassigned_session_id": false,
            "think": false,
            "speed": false
          },
          "version": "1.0.3",
          "description": "Hermes adapter using the native `hermes chat` executable and `--query` prompt binding while preserving provider-qualified model IDs."
        }
      ]
    }
  },
  {
    "id": "opencode",
    "label": "OpenCode",
    "binary": "opencode",
    "installHint": "Install OpenCode from https://opencode.ai/docs/cli (e.g. `npm i -g opencode-ai`) and ensure `opencode` resolves on PATH. Verify with `opencode run --help` — the similarly-named Go app some package managers ship has no `run` subcommand and will not work.",
    "version": "0.1.1",
    "homepage": "https://opencode.ai",
    "description": "OpenCode runtime adapter for Coven. Drives `opencode run` in both native launch modes and preserves provider-qualified model IDs; system prompts and tools are configured via project config (AGENTS.md / opencode.json).",
    "modelFlag": "--model",
    "modelIdTransform": "preserve",
    "capabilities": {
      "stream": false,
      "preassignedSessionId": false,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "opencode",
          "label": "OpenCode",
          "executable": "opencode",
          "interactive_prompt_prefix_args": [
            "run"
          ],
          "non_interactive_prompt_prefix_args": [
            "run"
          ],
          "install_hint": "Install OpenCode from https://opencode.ai/docs/cli (e.g. `npm i -g opencode-ai`) and ensure `opencode` resolves on PATH. Verify with `opencode run --help` — the similarly-named Go app some package managers ship has no `run` subcommand and will not work.",
          "model_flag": "--model",
          "model_id_transform": "preserve",
          "capabilities": {
            "stream": false,
            "preassigned_session_id": false,
            "think": false,
            "speed": false
          },
          "version": "0.1.1",
          "homepage": "https://opencode.ai",
          "description": "OpenCode runtime adapter for Coven. Drives `opencode run` in both native launch modes and preserves provider-qualified model IDs; system prompts and tools are configured via project config (AGENTS.md / opencode.json)."
        }
      ]
    }
  }
];
