Global {
    edge=bottom
    allign=left
    margin=0
    widthtype=percent
    width=100
    height=32
    transparent=0
    tintcolor=#130d1f
    alpha=255
    setdocktype=1
    setpartialstrut=1
    usefontcolor=1
    fontcolor=#f4efff
    usefontsize=1
    fontsize=10
    background=0
}

Plugin {
    type=menu
    Config {
        image=start-here
        system {
        }
        separator {
        }
        item {
            command=run
        }
    }
}

Plugin {
    type=space
    Config {
        Size=6
    }
}

Plugin {
    type=launchbar
    Config {
        Button {
            id=lxde-x-terminal-emulator.desktop
        }
    }
}

Plugin {
    type=taskbar
    expand=1
    Config {
        tooltips=1
        IconsOnly=0
        AcceptSkipPager=1
        ShowIconified=1
        ShowMapped=1
        ShowAllDesks=0
        UseMouseWheel=1
        UseUrgencyHint=1
        FlatButton=1
        MaxTaskWidth=180
        spacing=2
    }
}

Plugin {
    type=tray
}

Plugin {
    type=dclock
    Config {
        ClockFmt=%R
        TooltipFmt=%A %x
        BoldFont=0
    }
}
