"use client";

import { Icon as IconifyIcon, addCollection } from "@iconify/react";
// The picker offers one variant per Phosphor base name (prefer -fill); this
// trimmed catalog holds exactly those ~1.5k glyphs instead of the full ~9k-icon
// set, so the unused weight/duotone/thin variants don't ship. Generated by
// scripts/generate-icon-subset.mjs; glyph-catalog.ts reads the same file.
import phGlyphs from "@/lib/ph-glyph-catalog.json";
import { DEFAULT_FAMILIAR_GLYPH, type FamiliarGlyph as Glyph } from "@/lib/familiar-glyph";

// Names actually shipped in the trimmed catalog. A glyph naming an icon outside
// it (e.g. a daemon-supplied `ph:*` that isn't in our subset, or a weight
// variant we don't bundle) would render an empty box — fall back to the default
// so the avatar always shows *something*.
const BUNDLED_GLYPH_NAMES = new Set(
  Object.keys((phGlyphs as { icons?: Record<string, unknown> }).icons ?? {}).map((n) => `ph:${n}`),
);

/** The given glyph name if it's renderable, else the guaranteed-bundled default. */
function renderableGlyphName(name: string): string {
  return BUNDLED_GLYPH_NAMES.has(name) ? name : DEFAULT_FAMILIAR_GLYPH.name;
}

// ---------------------------------------------------------------------------
// Render component
//
// Why this lives outside `@/lib/icon`:
//   The chrome `<Icon>` component takes a strict `IconName` union over the
//   short registry of icons used by the app shell. The picker lets users
//   pick from any of Phosphor's ~1500 icons, so we'd otherwise have to dump
//   the entire catalogue into that union (defeating its purpose). Keeping a
//   second renderer here means user-content icons stay free-form while
//   chrome icons stay typo-safe.
// ---------------------------------------------------------------------------

let registered = false;
function ensureRegistered() {
  if (registered) return;
  addCollection(phGlyphs as Parameters<typeof addCollection>[0]);
  registered = true;
}

type Size = "sm" | "md" | "lg" | "xl";

const SIZE_PX: Record<Size, number> = {
  sm: 16,
  md: 22,
  lg: 36,
  xl: 48,
};

type Props = {
  glyph: Glyph;
  size?: Size;
  className?: string;
  title?: string;
};

export function FamiliarGlyph({ glyph, size = "md", className, title }: Props) {
  const px = SIZE_PX[size];

  ensureRegistered();
  return (
    <span
      className={className ?? "inline-flex items-center justify-center text-[var(--text-primary)]"}
      title={title}
    >
      <IconifyIcon
        icon={renderableGlyphName(glyph.name)}
        width={px}
        height={px}
        aria-label={title}
        role={title ? "img" : undefined}
      />
    </span>
  );
}
